# Written in Ansible version 2.7.6
# Author: Saurabh Saran


---
- name: Upgrade McAfee WebGateway Appliance Script (Release 7.8.2.5)
  hosts: all
  gather_facts: False

  tasks:

    - name: Performing Configuration Backup on the McAfee WebGateway
      command: /opt/mwg/bin/mwg-coordinator -B "file:in=ACTIVE,out=/tmp/current.backup"
      register:  print_output_1
      ignore_errors: True
    - debug:  var=print_output_1.stdout_lines

    - name: Creating Repository configuration for the sticky MWG (release 7.8.2.5)
      command: mwg-switch-repo --sticky 7.8.2.5
      register:  print_output_2
    - debug:  var=print_output_2.stdout_lines

    - name: Executing "yum upgrades yum" command
      command: yum -y upgrade yum
      register:  print_output_3
    - debug:  var=print_output_3.stdout_lines

    - name: Executing Yum Upgrades
      command: yum -y upgrade 
      register: print_output_4
      async: 3600
      poll: 30

    - name: Wait for the reboot and reconnect 
      wait_for:
        port: 22
        search_regex: OpenSSH
        delay: 10
        timeout: 60
      connection: local

    - name: McAfee WebGateway upgraded version    
      command: mwg-info version
      register: print_output_5
    - debug: var=print_output_5.stdout_lines

    - name: Signal a successful upgrade
      set_fact:
         install_status: "MWG Upgrade to Release 7.8.2.5 Completed."




