# Written in Ansible version 2.7.6
# Author: Saurabh Saran


---
- name: Upgrade McAfee WebGateway Appliance Script (Release 7.8.2.5)
  hosts: all
  gather_facts: False

  tasks:
   - name: Checking health of the Backup Web Gateway before Proceeding with the Upgrades
     hosts: mwg_secondary
     command: "{{ item }}"
     with_items:
         - ping 4.2.2.2
         - ping www.google.com
     register: ping_output
     debug: var=ping_output.stdout_lines
  
   - name: Capturing UUID of the McAfee Web Gateway
     command: cat uuid
     args:
         chdir: /etc/mwg
     register: mwg_uuid   


